// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArGitsdCc8ld80UnkRqyB3bUM02Af57io',
    appId: '1:79853440806:android:364644e1ce9f635118fbe7',
    messagingSenderId: '79853440806',
    projectId: 'chat-messenger-4464f',
    storageBucket: 'chat-messenger-4464f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoXxj7QzEeaIlVmHvyBuGKlbgF3ZvmP5I',
    appId: '1:79853440806:ios:179f750da69dc63e18fbe7',
    messagingSenderId: '79853440806',
    projectId: 'chat-messenger-4464f',
    storageBucket: 'chat-messenger-4464f.appspot.com',
    androidClientId: '79853440806-nt73o0ftac37ebecggbuki5fkou0m4d4.apps.googleusercontent.com',
    iosClientId: '79853440806-03qtl3fg7g0bb1lu9dc07r8tcell1vv8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatMessenger',
  );
}
